version: "3.8"

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.prod
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=app.config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_prod
      - SECRET_KEY=secret
    depends_on:
      - db

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
        - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5004
    ports:
      - 3007:80
    depends_on:
      - backend
